name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  test-default:
    name: test (default features)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo build
        run: cargo build --release --verbose
      - name: cargo test
        run: cargo test --release --verbose

  test-parallel-cpu:
    name: test (parallel-cpu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo build (parallel-cpu)
        run: cargo build --release --features parallel-cpu --verbose
      - name: cargo test (parallel-cpu)
        run: cargo test --release --features parallel-cpu --verbose

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
